"""add migrate create log table

Revision ID: 1248a759e98e
Revises: 5e1b814d8c45
Create Date: 2017-03-09 23:33:15.769420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1248a759e98e'
down_revision = '5e1b814d8c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_time', sa.DateTime(), nullable=True),
    sa.Column('user_telegram_id', sa.Integer(), nullable=True),
    sa.Column('user_telegram_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot-logger')
    # ### end Alembic commands ###
