"""duration & rating in Movies Integer, default = 0

Revision ID: 2f4f3740bdce
Revises: a1a3bf8783e1
Create Date: 2017-02-08 19:31:05.468435

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2f4f3740bdce'
down_revision = 'a1a3bf8783e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'duration',
                    existing_type=sa.VARCHAR(length=120),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using='duration::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'duration',
                    existing_type=sa.Float(),
                    type_=sa.VARCHAR(length=120),
                    existing_nullable=True,
                    postgresql_using='duration::varchar(120)')
    # ### end Alembic commands ###
