"""time_slot_uniqueness

Revision ID: 3caa079a6a77
Revises: b63d7a5bda8e
Create Date: 2017-02-19 19:52:15.388908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caa079a6a77'
down_revision = 'b63d7a5bda8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('time_slot_uniqueness', 'time_slots', ['movie_theaters_id', 'movie_id',
                                                                       'movie_formats_id', 'time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('time_slot_uniqueness', 'time_slots', type_='unique')
    # ### end Alembic commands ###
