"""init base schema

Revision ID: 843b8263c8d4
Revises: 
Create Date: 2017-02-03 19:37:36.322375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843b8263c8d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metro_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_movie_id', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies_tmdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tmdb_plot_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('movie_theaters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metro_id', sa.Integer(), nullable=True),
    sa.Column('yandex_theater_id', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone1', sa.String(length=500), nullable=True),
    sa.Column('phone2', sa.String(length=500), nullable=True),
    sa.Column('phone3', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['metro_id'], ['metro_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_plot_keywords_connecction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['tmdb_plot_keywords.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies_tmdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_theaters_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_formats_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_formats_id'], ['movie_formats.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['movie_theaters_id'], ['movie_theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_slots')
    op.drop_table('tmdb_plot_keywords_connecction')
    op.drop_table('movie_theaters')
    op.drop_table('tmdb_plot_keywords')
    op.drop_table('movies_tmdb')
    op.drop_table('movies')
    op.drop_table('movie_formats')
    op.drop_table('metro_stations')
    # ### end Alembic commands ###
