"""add_movie_status_and_date_create

Revision ID: 87dbba7785d6
Revises: 465b11daf417
Create Date: 2017-03-17 22:37:22.260669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dbba7785d6'
down_revision = '465b11daf417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('movie_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'movie_status')
    op.drop_column('movies', 'create_date')
    # ### end Alembic commands ###
