"""Merged movies&tmdb_movies in one table

Revision ID: a1a3bf8783e1
Revises: ae01df338c6b
Create Date: 2017-02-06 23:11:12.707517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a3bf8783e1'
down_revision = 'ae01df338c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tmdb_plot_keywords_connecction_movie_id_fkey', 'tmdb_plot_keywords_connecction', type_='foreignkey')
    op.drop_table('movies_tmdb')
    op.add_column('movies', sa.Column('genre', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'tmdb_plot_keywords_connecction', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tmdb_plot_keywords_connecction', type_='foreignkey')
    op.create_foreign_key('tmdb_plot_keywords_connecction_movie_id_fkey', 'tmdb_plot_keywords_connecction', 'movies_tmdb', ['movie_id'], ['id'])
    op.drop_column('movies', 'genre')
    op.create_table('movies_tmdb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='movies_tmdb_pkey'),
    sa.UniqueConstraint('title', name='movies_tmdb_title_key')
    )
    # ### end Alembic commands ###
