"""add-UniqueConstraint-movie_uniqueness

Revision ID: b4ebaa26c78a
Revises: 843b8263c8d4
Create Date: 2017-02-04 12:28:30.262476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ebaa26c78a'
down_revision = '843b8263c8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movie_uniqueness', 'movies', ['yandex_movie_id', 'title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_uniqueness', 'movies', type_='unique')
    # ### end Alembic commands ###
