"""Set rating as a float

Revision ID: b63d7a5bda8e
Revises: 2f4f3740bdce
Create Date: 2017-02-11 17:59:08.160329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63d7a5bda8e'
down_revision = '2f4f3740bdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Float(),
               postgresql_using='trim(rating)::float',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
