"""create_date_for_report

Revision ID: c26b4ab9dc37
Revises: 9188048d8d0a
Create Date: 2017-08-25 00:07:58.068491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26b4ab9dc37'
down_revision = '9188048d8d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metro_stations', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('movie_theaters', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_theaters', 'created_time')
    op.drop_column('metro_stations', 'created_time')
    # ### end Alembic commands ###
