"""first migration

Revision ID: e39e9199d205
Revises: 
Create Date: 2017-02-03 00:08:19.522717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e39e9199d205'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('metro_stations_title_key', 'metro_stations', type_='unique')
    op.add_column('movie_theaters', sa.Column('yandex_theater_id', sa.String(length=140), nullable=True))
    op.add_column('movies', sa.Column('yandex_movie_id', sa.String(length=140), nullable=True))
    op.add_column('time_slots', sa.Column('max_price', sa.Integer(), nullable=True))
    op.add_column('time_slots', sa.Column('min_price', sa.Integer(), nullable=True))
    op.drop_column('time_slots', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('time_slots', 'min_price')
    op.drop_column('time_slots', 'max_price')
    op.drop_column('movies', 'yandex_movie_id')
    op.drop_column('movie_theaters', 'yandex_theater_id')
    op.create_unique_constraint('metro_stations_title_key', 'metro_stations', ['title'])
    # ### end Alembic commands ###
